# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-12 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goskyhy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='hashtags',
            field=models.ManyToManyField(related_name='stories_hashtags', to='goskyhy.Hashtags'),
        ),
        migrations.AddField(
            model_name='stories',
            name='tags',
            field=models.ManyToManyField(related_name='stories_tags', to='goskyhy.Tags'),
        ),
    ]
