# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-17 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goskyhy', '0003_experiences_times'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('alt_text', models.CharField(max_length=255)),
                ('credit', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='experiences',
            name='tag',
            field=models.ManyToManyField(related_name='exp_tags', to='goskyhy.Tags'),
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='exp',
        ),
        migrations.AddField(
            model_name='reviews',
            name='exp',
            field=models.ManyToManyField(related_name='review_exp', to='goskyhy.Experiences'),
        ),
        migrations.AddField(
            model_name='stories',
            name='images',
            field=models.ManyToManyField(related_name='stories_images', to='goskyhy.Images'),
        ),
    ]
