# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-17 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goskyhy', '0004_auto_20190617_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiences',
            name='picture',
            field=models.ManyToManyField(related_name='exp_pictures', to='goskyhy.Pictures'),
        ),
    ]
