# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-17 22:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goskyhy', '0006_auto_20190617_1511'),
    ]

    operations = [
    ]
