# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-18 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goskyhy', '0007_remove_stories_unique_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='image_user', to='goskyhy.Users'),
            preserve_default=False,
        ),
    ]
