# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-20 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goskyhy', '0009_auto_20190618_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='exp',
        ),
        migrations.RemoveField(
            model_name='images',
            name='story',
        ),
        migrations.AddField(
            model_name='stories',
            name='images',
            field=models.ManyToManyField(related_name='stories_images', to='goskyhy.Images'),
        ),
    ]
