# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-27 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goskyhy', '0010_auto_20190619_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictures',
            name='story',
        ),
        migrations.RemoveField(
            model_name='pictures',
            name='user',
        ),
        migrations.RemoveField(
            model_name='experiences',
            name='picture',
        ),
        migrations.AddField(
            model_name='experiences',
            name='images',
            field=models.ManyToManyField(related_name='exp_images', to='goskyhy.Images'),
        ),
        migrations.DeleteModel(
            name='Pictures',
        ),
    ]
