# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-03 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goskyhy', '0011_auto_20190627_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='userpro',
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='profile_pic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prof_images', to='goskyhy.Images'),
        ),
    ]
