# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-03 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goskyhy', '0012_auto_20190703_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prof_user', to='goskyhy.Users'),
        ),
    ]
