# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-03 21:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goskyhy', '0013_auto_20190703_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiles',
            name='curr_city',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='prof_curr_city', to='goskyhy.Cities'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='og_city',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='prof_og_city', to='goskyhy.Cities'),
            preserve_default=False,
        ),
    ]
