# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-08 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goskyhy', '0014_auto_20190703_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiences',
            name='tag',
            field=models.ManyToManyField(related_name='exp_tags', to='goskyhy.Hashtags'),
        ),
    ]
