# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-16 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goskyhy', '0015_auto_20190708_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiles',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='userprof_users', to='goskyhy.Users'),
        ),
    ]
