# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-22 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goskyhy', '0017_auto_20190719_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('notes', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_accepted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_exp_user', to='goskyhy.Users')),
            ],
        ),
        migrations.CreateModel(
            name='ExperiencesUnvalidated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('host', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('distance', models.CharField(max_length=255)),
                ('provided', models.CharField(max_length=255)),
                ('details', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exp_status', to='goskyhy.AcceptedExperience')),
                ('agree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='un_exp_agree', to='goskyhy.Agrees')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='un_exp_categories', to='goskyhy.Categories')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='un_exp_city', to='goskyhy.Cities')),
                ('english', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='un_exp_english', to='goskyhy.Language')),
                ('images', models.ManyToManyField(related_name='un_exp_images', to='goskyhy.Images')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='un_exp_location', to='goskyhy.Locations')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='un_exp_price', to='goskyhy.Prices')),
                ('tag', models.ManyToManyField(related_name='un_exp_tags', to='goskyhy.Hashtags')),
                ('times', models.ManyToManyField(related_name='un_exps_times', to='goskyhy.Times')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='un_exp_user', to='goskyhy.Users')),
            ],
        ),
        migrations.CreateModel(
            name='FriendValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_receiving', to='goskyhy.Users')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sending', to='goskyhy.Users')),
            ],
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='all_friends',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='background',
            field=models.TextField(default=''),
        ),
    ]
