# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-22 22:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goskyhy', '0019_userprofiles_to_validate'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendValidationReceiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('validation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_validation', to='goskyhy.FriendValidation')),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofiles',
            name='to_validate',
        ),
    ]
