# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-23 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goskyhy', '0021_userprofiles_to_validate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendvalidationreceiver',
            name='validation',
        ),
        migrations.RemoveField(
            model_name='userprofiles',
            name='to_validate',
        ),
        migrations.AddField(
            model_name='friendvalidation',
            name='confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='FriendValidationReceiver',
        ),
    ]
