# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-23 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goskyhy', '0022_auto_20190722_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiles',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
