# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-24 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goskyhy', '0023_auto_20190723_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='total_cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='orders',
            name='total_items',
            field=models.IntegerField(default=0),
        ),
    ]
