# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-29 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goskyhy', '0024_auto_20190723_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofiles',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofiles',
            name='last_name',
        ),
        migrations.AddField(
            model_name='users',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
