# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-30 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goskyhy', '0026_auto_20190730_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='curr_city',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='prof_curr_city', to='goskyhy.Cities'),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='og_city',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='prof_og_city', to='goskyhy.Cities'),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='profile_pic',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='prof_images', to='goskyhy.Images'),
        ),
    ]
